Attribute VB_Name = "七类料重字段名"
Sub 七类料重字段名()
Attribute 七类料重字段名.VB_Description = "宏由 jr.l 录制，时间: 2018-4-14"
Attribute 七类料重字段名.VB_ProcData.VB_Invoke_Func = " \n14"
Cells(1, 1).Value = "workbook.path"
Cells(1, 2).Value = "workbook.name"
Cells(1, 3).Value = "worksheets.name"
Cells(1, 4).Value = "顾客代码"
Cells(1, 5).Value = "产品型号"
Cells(1, 6).Value = "产品材质"
Cells(1, 7).Value = "主材料厚"
Cells(1, 8).Value = "小端外径"
Cells(1, 9).Value = "大端外径"
Cells(1, 10).Value = "幅高"
Cells(1, 11).Value = "料直径"
Cells(1, 12).Value = "适用主材料宽"
Cells(1, 13).Value = "料片净重"
Cells(1, 14).Value = "料片毛重"
End Sub
