Attribute VB_Name = "零类包装材料字段名"
Sub 零类包装材料字段名()
Cells(1, 1).Value = "workbook.path"
Cells(1, 2).Value = "workbook.name"
Cells(1, 3).Value = "worksheets.name"
Cells(1, 4).Value = "顾客代码"
Cells(1, 5).Value = "型号"
Cells(1, 6).Value = "料厚"
Cells(1, 7).Value = "类型"
Cells(1, 8).Value = "卷装件数"
Cells(1, 9).Value = "箱装件数"
Cells(1, 10).Value = "箱装卷数"
Cells(1, 11).Value = "箱子尺寸"
Cells(1, 12).Value = "箱子数量"
Cells(1, 13).Value = "pcv管规格"
Cells(1, 14).Value = "pcv管数量"
Cells(1, 15).Value = "皮套规格"
Cells(1, 16).Value = "皮套数量"
Cells(1, 17).Value = "pe塑料袋规格"
Cells(1, 18).Value = "pe塑料袋数量"
Cells(1, 19).Value = "合格证规格"
Cells(1, 20).Value = "合格证数量"
Cells(1, 21).Value = "不干标签规格"
Cells(1, 22).Value = "不干标签数量"
End Sub
